openapi: 3.0.0
info:
  title: RocketCart Storefront API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Search Shopify products
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: false
          description: Text search for products
      responses:
        '200':
          description: A list of products
  /cart:
    post:
      summary: Create a shopping cart
      responses:
        '200':
          description: Cart created
  /checkout:
    post:
      summary: Generate checkout URL
      responses:
        '200':
          description: Checkout URL returned
